### ISSUE TITLE
limiter never frees up

### ISSUE THREAD

**Issue by rickyk586** [tj/node-ratelimiter#45]
```
const RateLimiter = require('ratelimiter')
//const RateLimiter = require('.')
const Redis = require('ioredis')
const { promisify } = require('util')

const limiter = new RateLimiter({
  duration: 2000,
  max: 2,
  id: 'something',
  db: new Redis()
})

const get = promisify(limiter.get.bind(limiter))

let index = -1
setInterval(async () => {
  console.log('---')
  console.log('iteration', ++index)
  const r = await get()
  console.log('value', r)
}, 100)
```
r.remaining goes to 0 and stays at 0. it's expected to release at least 1 every 2 seconds.

initial issue on sub-project: https://github.com/microlinkhq/async-ratelimiter/issues/11

**Comment by noamshemesh** [comment]
Thanks @rickyk586 for pointing that out.
Although, this is by design. A request decreases the (imaginary) counter. 
In other words there is a window of 2 seconds in your case and if there are more than 2 requests (even though they were not served by the server) in it, another request won't be allowed.

**Comment by rickyk586** [comment]
I would assume that another request would eventually be allowed (after the window of 2 seconds).
